// import { Book, Borrower, Borrowing, RecentActivity } from '../types';

import type { Book, Borrower, Borrowing, RecentActivity,  } from "@/types";

export const INITIAL_BORROWERS: Borrower[] = [
  {
    id: 'bor-1',
    name: 'Thomas Dubois',
    email: 'thomas.dubois@acme.dev',
    phone: '+33 6 12 34 56 78',
    membership_date: '2024-01-15',
    status: 'active',
    current_borrowings_count: 1,
    total_borrowings_count: 5,
    created_at: '2024-01-15T09:00:00Z',
  },
  {
    id: 'bor-2',
    name: 'Sophie Martin',
    email: 'sophie.martin@techlabs.io',
    phone: '+33 6 98 76 54 32',
    membership_date: '2024-02-01',
    status: 'active',
    current_borrowings_count: 1,
    total_borrowings_count: 3,
    created_at: '2024-02-01T10:30:00Z',
  },
  {
    id: 'bor-3',
    name: 'Alexandre Laurent',
    email: 'a.laurent@polytechnique.edu',
    phone: '+33 6 45 67 89 01',
    membership_date: '2024-03-10',
    status: 'active',
    current_borrowings_count: 1,
    total_borrowings_count: 4,
    created_at: '2024-03-10T14:15:00Z',
  },
  {
    id: 'bor-4',
    name: 'Camille Bernard',
    email: 'camille.b@creative-studio.fr',
    phone: '+33 7 89 01 23 45',
    membership_date: '2024-04-05',
    status: 'active',
    current_borrowings_count: 0,
    total_borrowings_count: 2,
    created_at: '2024-04-05T11:00:00Z',
  },
  {
    id: 'bor-5',
    name: 'Lucas Petit',
    email: 'lucas.petit@cloudscale.net',
    phone: '+33 6 77 88 99 00',
    membership_date: '2024-05-12',
    status: 'active',
    current_borrowings_count: 0,
    total_borrowings_count: 1,
    created_at: '2024-05-12T16:45:00Z',
  },
];

export const INITIAL_BOOKS: Book[] = [
  {
    id: 'bk-1',
    title: 'Clean Architecture',
    author: 'Robert C. Martin',
    isbn: '978-0134494166',
    published_year: 2017,
    category: 'Architecture Logicielle',
    description: 'Un guide incontournable pour structurer des applications robustes, testables et indépendantes des frameworks.',
    status: 'available',
    current_borrowing: null,
    total_borrowings_count: 8,
    created_at: '2024-01-10T10:00:00Z',
  },
  {
    id: 'bk-2',
    title: 'The Pragmatic Programmer',
    author: 'Andrew Hunt & David Thomas',
    isbn: '978-0135957059',
    published_year: 2019,
    category: 'Génie Logiciel',
    description: 'Vingt ans après sa première édition, ce classique reste la référence pour passer du statut d’artisan du code à celui de développeur pragmatique.',
    status: 'borrowed',
    current_borrowing: {
      id: 'bw-1',
      borrower_id: 'bor-1',
      borrower_name: 'Thomas Dubois',
      borrower_email: 'thomas.dubois@acme.dev',
      borrowed_at: '2026-08-18',
      due_date: '2026-09-08',
    },
    total_borrowings_count: 12,
    created_at: '2024-01-10T10:05:00Z',
  },
  {
    id: 'bk-3',
    title: 'Design Patterns',
    author: 'Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides',
    isbn: '978-0201633610',
    published_year: 1994,
    category: 'Conception Orientée Objet',
    description: 'Le célèbre ouvrage du "Gang of Four" répertoriant 23 patrons de conception fondamentaux du génie logiciel.',
    status: 'available',
    current_borrowing: null,
    total_borrowings_count: 6,
    created_at: '2024-01-12T11:20:00Z',
  },
  {
    id: 'bk-4',
    title: 'Refactoring',
    author: 'Martin Fowler',
    isbn: '978-0134757599',
    published_year: 2018,
    category: 'Qualité de Code',
    description: 'Techniques éprouvées pour améliorer la conception du code existant sans en modifier le comportement externe.',
    status: 'borrowed',
    current_borrowing: {
      id: 'bw-2',
      borrower_id: 'bor-2',
      borrower_name: 'Sophie Martin',
      borrower_email: 'sophie.martin@techlabs.io',
      borrowed_at: '2026-08-10',
      due_date: '2026-08-31', // Overdue relative to current date (Sept 1, 2026)
    },
    total_borrowings_count: 9,
    created_at: '2024-01-15T09:30:00Z',
  },
  {
    id: 'bk-5',
    title: 'Domain-Driven Design',
    author: 'Eric Evans',
    isbn: '978-0321125217',
    published_year: 2003,
    category: 'Architecture Métier',
    description: 'L’ouvrage fondateur qui place le modèle de domaine au cœur de la conception logicielle face à des règles métier complexes.',
    status: 'available',
    current_borrowing: null,
    total_borrowings_count: 5,
    created_at: '2024-01-18T14:00:00Z',
  },
  {
    id: 'bk-6',
    title: 'Designing Data-Intensive Applications',
    author: 'Martin Kleppmann',
    isbn: '978-1449373320',
    published_year: 2017,
    category: 'Systèmes Distribués',
    description: 'Analyse exhaustive et pragmatique des principes sous-jacents aux architectures de données scalables et fiables.',
    status: 'available',
    current_borrowing: null,
    total_borrowings_count: 11,
    created_at: '2024-02-01T15:00:00Z',
  },
  {
    id: 'bk-7',
    title: 'Building Microservices',
    author: 'Sam Newman',
    isbn: '978-1492034025',
    published_year: 2021,
    category: 'Cloud & Microservices',
    description: 'Guide complet pour modéliser, intégrer, déployer et sécuriser des systèmes basés sur les microservices.',
    status: 'available',
    current_borrowing: null,
    total_borrowings_count: 7,
    created_at: '2024-02-15T08:45:00Z',
  },
  {
    id: 'bk-8',
    title: 'Site Reliability Engineering',
    author: 'Betsy Beyer, Chris Jones, Jennifer Petoff, Niall Murphy',
    isbn: '978-1491929124',
    published_year: 2016,
    category: 'DevOps & Fiabilité',
    description: 'Retours d’expérience de Google sur l’exploitation de systèmes distribués à très grande échelle.',
    status: 'borrowed',
    current_borrowing: {
      id: 'bw-3',
      borrower_id: 'bor-3',
      borrower_name: 'Alexandre Laurent',
      borrower_email: 'a.laurent@polytechnique.edu',
      borrowed_at: '2026-08-25',
      due_date: '2026-09-15',
    },
    total_borrowings_count: 4,
    created_at: '2024-03-01T12:00:00Z',
  },
];

export const INITIAL_BORROWINGS: Borrowing[] = [
  {
    id: 'bw-1',
    book_id: 'bk-2',
    book_title: 'The Pragmatic Programmer',
    book_author: 'Andrew Hunt & David Thomas',
    borrower_id: 'bor-1',
    borrower_name: 'Thomas Dubois',
    borrower_email: 'thomas.dubois@acme.dev',
    borrowed_at: '2026-08-18',
    due_date: '2026-09-08',
    returned_at: null,
    status: 'active',
  },
  {
    id: 'bw-2',
    book_id: 'bk-4',
    book_title: 'Refactoring',
    book_author: 'Martin Fowler',
    borrower_id: 'bor-2',
    borrower_name: 'Sophie Martin',
    borrower_email: 'sophie.martin@techlabs.io',
    borrowed_at: '2026-08-10',
    due_date: '2026-08-31',
    returned_at: null,
    status: 'overdue',
  },
  {
    id: 'bw-3',
    book_id: 'bk-8',
    book_title: 'Site Reliability Engineering',
    book_author: 'Betsy Beyer et al.',
    borrower_id: 'bor-3',
    borrower_name: 'Alexandre Laurent',
    borrower_email: 'a.laurent@polytechnique.edu',
    borrowed_at: '2026-08-25',
    due_date: '2026-09-15',
    returned_at: null,
    status: 'active',
  },
  // Historical returned borrowings
  {
    id: 'bw-hist-1',
    book_id: 'bk-1',
    book_title: 'Clean Architecture',
    book_author: 'Robert C. Martin',
    borrower_id: 'bor-1',
    borrower_name: 'Thomas Dubois',
    borrower_email: 'thomas.dubois@acme.dev',
    borrowed_at: '2026-07-01',
    due_date: '2026-07-22',
    returned_at: '2026-07-20',
    status: 'returned',
  },
  {
    id: 'bw-hist-2',
    book_id: 'bk-3',
    book_title: 'Design Patterns',
    book_author: 'Erich Gamma et al.',
    borrower_id: 'bor-4',
    borrower_name: 'Camille Bernard',
    borrower_email: 'camille.b@creative-studio.fr',
    borrowed_at: '2026-07-15',
    due_date: '2026-08-05',
    returned_at: '2026-08-03',
    status: 'returned',
  },
  {
    id: 'bw-hist-3',
    book_id: 'bk-6',
    book_title: 'Designing Data-Intensive Applications',
    book_author: 'Martin Kleppmann',
    borrower_id: 'bor-3',
    borrower_name: 'Alexandre Laurent',
    borrower_email: 'a.laurent@polytechnique.edu',
    borrowed_at: '2026-06-10',
    due_date: '2026-07-01',
    returned_at: '2026-06-29',
    status: 'returned',
  },
  {
    id: 'bw-hist-4',
    book_id: 'bk-5',
    book_title: 'Domain-Driven Design',
    book_author: 'Eric Evans',
    borrower_id: 'bor-2',
    borrower_name: 'Sophie Martin',
    borrower_email: 'sophie.martin@techlabs.io',
    borrowed_at: '2026-06-20',
    due_date: '2026-07-11',
    returned_at: '2026-07-09',
    status: 'returned',
  },
];

export const INITIAL_ACTIVITIES: RecentActivity[] = [
  {
    id: 'act-1',
    type: 'borrow',
    title: 'Nouvel emprunt enregistré',
    description: 'Alexandre Laurent a emprunté "Site Reliability Engineering"',
    timestamp: '2026-08-25T14:30:00Z',
    book_id: 'bk-8',
    borrower_id: 'bor-3',
  },
  {
    id: 'act-2',
    type: 'borrow',
    title: 'Nouvel emprunt enregistré',
    description: 'Thomas Dubois a emprunté "The Pragmatic Programmer"',
    timestamp: '2026-08-18T10:15:00Z',
    book_id: 'bk-2',
    borrower_id: 'bor-1',
  },
  {
    id: 'act-3',
    type: 'return',
    title: 'Retour confirmé',
    description: 'Camille Bernard a retourné "Design Patterns"',
    timestamp: '2026-08-03T16:20:00Z',
    book_id: 'bk-3',
    borrower_id: 'bor-4',
  },
  {
    id: 'act-4',
    type: 'book_added',
    title: 'Livre ajouté au catalogue',
    description: '"Building Microservices" par Sam Newman',
    timestamp: '2026-08-01T09:00:00Z',
    book_id: 'bk-7',
  },
];
